project_id = "hvtrpkbjgbuypkskqcqm"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://670105f7-06c6-4b08-bcbc-08cdf03b5546.lovableproject.com/**", "https://descubra-ms.lovable.app/**", "https://id-preview--670105f7-06c6-4b08-bcbc-08cdf03b5546.lovable.app/**", "https://preview--descubra-ms.lovable.app/**", "http://localhost:3000", "http://localhost:3000/*"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.mfa]
max_enrolled_factors = 10
[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 86400
[auth.email.template]

[auth.sms]
enable_signup = false