// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/search-events.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.23.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.39.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (ou VITE_SUPABASE_URL) \xE9 obrigat\xF3rio");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS ou SUPABASE_ANON_KEY \xE9 obrigat\xF3rio");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser exige um token OAuth verificado");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-events.ts
var search_events_default = defineTool({
  name: "search_events",
  title: "Buscar eventos",
  description: "Busca eventos tur\xEDsticos aprovados e vis\xEDveis do Descubra MS. Filtra por cidade, categoria e per\xEDodo.",
  inputSchema: {
    query: z.string().optional().describe("Palavra-chave no t\xEDtulo do evento."),
    city: z.string().optional().describe("Cidade em MS, ex.: 'Bonito'."),
    category: z.string().optional().describe("Categoria do evento."),
    from_date: z.string().optional().describe("Data inicial YYYY-MM-DD (padr\xE3o: hoje)."),
    limit: z.number().int().optional().describe("M\xE1ximo de resultados (padr\xE3o 10, m\xE1x 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const limit = Math.min(Math.max(input.limit ?? 10, 1), 50);
    const from = input.from_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    let q = supabase.from("events").select("id, titulo, descricao, data_inicio, data_fim, local, cidade, categoria, tipo_entrada, organizador, site_oficial, imagem_principal, is_sponsored").eq("approval_status", "approved").eq("is_visible", true).gte("data_inicio", from).order("data_inicio", { ascending: true }).limit(limit);
    if (input.query) q = q.ilike("titulo", `%${input.query}%`);
    if (input.city) q = q.ilike("cidade", `%${input.city}%`);
    if (input.category) q = q.ilike("categoria", `%${input.category}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-partners.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.23.3";
var search_partners_default = defineTool2({
  name: "search_partners",
  title: "Buscar parceiros",
  description: "Busca parceiros ativos e aprovados do Descubra MS (pousadas, restaurantes, ag\xEAncias, atrativos).",
  inputSchema: {
    query: z2.string().optional().describe("Nome ou palavra-chave do parceiro."),
    partner_type: z2.string().optional().describe("Tipo de parceiro (opcional)."),
    limit: z2.number().int().optional().describe("M\xE1ximo de resultados (padr\xE3o 10, m\xE1x 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const limit = Math.min(Math.max(input.limit ?? 10, 1), 50);
    let q = supabase.from("institutional_partners").select("id, name, description, partner_type, website_url, contact_email, contact_phone, logo_url").eq("is_active", true).order("name", { ascending: true }).limit(limit);
    if (input.query) q = q.ilike("name", `%${input.query}%`);
    if (input.partner_type) q = q.ilike("partner_type", `%${input.partner_type}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { partners: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-passport-routes.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.23.3";
var list_passport_routes_default = defineTool3({
  name: "list_passport_routes",
  title: "Listar roteiros do passaporte",
  description: "Lista roteiros publicados do Passaporte Digital do Descubra MS, com dificuldade, dura\xE7\xE3o e n\xFAmero de dias. Passe route_id para receber tamb\xE9m os checkpoints do roteiro.",
  inputSchema: {
    route_id: z3.string().optional().describe("UUID do roteiro para detalhar checkpoints."),
    region: z3.string().optional().describe("Regi\xE3o tur\xEDstica (opcional)."),
    limit: z3.number().int().optional().describe("M\xE1ximo de roteiros (padr\xE3o 20, m\xE1x 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    if (input.route_id) {
      const { data: route, error: error2 } = await supabase.from("routes").select("id, name, description, region, difficulty, estimated_duration, total_days, checkpoint_order_mode, google_maps_embed_url, image_url").eq("id", input.route_id).eq("is_published", true).maybeSingle();
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      if (!route) return { content: [{ type: "text", text: "Roteiro n\xE3o encontrado." }], isError: true };
      const { data: checkpoints, error: cpErr } = await supabase.from("route_checkpoints").select("*").eq("route_id", input.route_id);
      if (cpErr) return { content: [{ type: "text", text: cpErr.message }], isError: true };
      const payload = { route, checkpoints: checkpoints ?? [] };
      return {
        content: [{ type: "text", text: JSON.stringify(payload) }],
        structuredContent: payload
      };
    }
    const limit = Math.min(Math.max(input.limit ?? 20, 1), 50);
    let q = supabase.from("routes").select("id, name, description, region, difficulty, estimated_duration, total_days, checkpoint_order_mode").eq("is_published", true).order("name", { ascending: true }).limit(limit);
    if (input.region) q = q.ilike("region", `%${input.region}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { routes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-passport-progress.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.23.3";
var get_my_passport_progress_default = defineTool4({
  name: "get_my_passport_progress",
  title: "Meu progresso no passaporte",
  description: "Retorna os selos (check-ins) do Passaporte Digital do usu\xE1rio logado, com pontos acumulados. Opcionalmente filtra por roteiro.",
  inputSchema: {
    route_id: z4.string().optional().describe("UUID do roteiro para filtrar (opcional)."),
    limit: z4.number().int().optional().describe("M\xE1ximo de selos (padr\xE3o 50, m\xE1x 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const limit = Math.min(Math.max(input.limit ?? 50, 1), 200);
    let q = supabase.from("passport_stamps").select("id, route_id, checkpoint_id, destination_id, stamp_type, activity_type, points_earned, stamped_at").eq("user_id", ctx.getUserId()).order("stamped_at", { ascending: false }).limit(limit);
    if (input.route_id) q = q.eq("route_id", input.route_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const stamps = data ?? [];
    const payload = {
      total_stamps: stamps.length,
      total_points: stamps.reduce((sum, s) => sum + (Number(s.points_earned) || 0), 0),
      stamps
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-my-reservations.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.23.3";
var list_my_reservations_default = defineTool5({
  name: "list_my_reservations",
  title: "Minhas reservas",
  description: "Lista as reservas do usu\xE1rio logado com parceiros do Descubra MS (status, valor, c\xF3digo e datas).",
  inputSchema: {
    status: z5.string().optional().describe("Filtrar por status, ex.: 'pending', 'confirmed', 'cancelled'."),
    limit: z5.number().int().optional().describe("M\xE1ximo de reservas (padr\xE3o 20, m\xE1x 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const limit = Math.min(Math.max(input.limit ?? 20, 1), 100);
    let q = supabase.from("partner_reservations").select("id, reservation_code, partner_id, service_name, reservation_date, reservation_time, check_in_date, check_out_date, guests, total_amount, status, payment_status, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (input.status) q = q.eq("status", input.status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { reservations: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hvtrpkbjgbuypkskqcqm";
var mcp_default = defineMcp({
  name: "descubra-ms",
  title: "descubra-ms",
  version: "0.1.0",
  instructions: "Ferramentas do Descubra MS (turismo de Mato Grosso do Sul). Use `search_events` para eventos, `search_partners` para parceiros, `list_passport_routes` para roteiros do Passaporte Digital, `get_my_passport_progress` para os selos do usu\xE1rio logado e `list_my_reservations` para as reservas dele. Todas as ferramentas agem como o usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_events_default,
    search_partners_default,
    list_passport_routes_default,
    get_my_passport_progress_default,
    list_my_reservations_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
