// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgrpelcbzuyuqjjlnwws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhncnBlbGNienV5dXFqamxud3dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NzI2MjMsImV4cCI6MjA2NjA0ODYyM30.ILbK5KZ0aGJ2Jw4TmWN33HaWYWddtRfksX932wtp1A8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});